/**
 * Generates a style object for the block based on provided tab styles.
 *
 * @param {Object} tabStyles - The styles for the tabs.
 * @return {Object} The style object to be applied to the block.
 */
export const getBlockStyles = ( tabStyles ) => {
    return {
        [`--tabs-gap`]: tabStyles?.tabsGap || null,
        [`--tabs-min-height`]: tabStyles?.tabsMinHeight || null,
        [`--tabs-color`]: tabStyles?.tabsColor || null,
        [`--tabs-bg-color`]: tabStyles?.tabsBgColor || null,
        [`--tabs-border-color`]: tabStyles?.tabsBorder?.color || null,
        [`--tabs-border-style`]: tabStyles?.tabsBorder?.style || null,
        [`--tabs-border-width`]: tabStyles?.tabsBorder?.width || null,
        [`--tabs-border-top-color`]: tabStyles?.tabsBorder?.top?.color || null,
        [`--tabs-border-top-style`]: tabStyles?.tabsBorder?.top?.style || null,
        [`--tabs-border-top-width`]: tabStyles?.tabsBorder?.top?.width || null,
        [`--tabs-border-right-color`]: tabStyles?.tabsBorder?.right?.color || null,
        [`--tabs-border-right-style`]: tabStyles?.tabsBorder?.right?.style || null,
        [`--tabs-border-right-width`]: tabStyles?.tabsBorder?.right?.width || null,
        [`--tabs-border-bottom-color`]: tabStyles?.tabsBorder?.bottom?.color || null,
        [`--tabs-border-bottom-style`]: tabStyles?.tabsBorder?.bottom?.style || null,
        [`--tabs-border-bottom-width`]: tabStyles?.tabsBorder?.bottom?.width || null,
        [`--tabs-border-left-color`]: tabStyles?.tabsBorder?.left?.color || null,
        [`--tabs-border-left-style`]: tabStyles?.tabsBorder?.left?.style || null,
        [`--tabs-border-left-width`]: tabStyles?.tabsBorder?.left?.width || null,
        [`--labels-font-size`]: tabStyles?.labelsFontSize || null,
        [`--label-max-width`]: tabStyles?.labelsMaxWidth || null,
        [`--labels-bg-color`]: tabStyles?.labelsBgColor || null,
        [`--labels-bg-color-active`]: tabStyles?.labelsBgColorActive || null,
        [`--labels-color`]: tabStyles?.labelsColor || null,
        [`--labels-color-active`]: tabStyles?.labelsColorActive || null,
        [`--labels-gap`]: tabStyles?.labelsGap || null,
        [`--labels-padding`]: tabStyles?.labelsPadding || null,
        [`--labels-border-color`]: tabStyles?.labelsBorder?.color || null,
        [`--labels-border-style`]: tabStyles?.labelsBorder?.style || null,
        [`--labels-border-width`]: tabStyles?.labelsBorder?.width || null,
        [`--labels-border-active-color`]: tabStyles?.labelsBorderActive?.color || null,
        [`--labels-border-active-style`]: tabStyles?.labelsBorderActive?.style || null,
        [`--labels-border-active-width`]: tabStyles?.labelsBorderActive?.width || null,
        [`--labels-border-top-color`]: tabStyles?.labelsBorder?.top?.color || null,
        [`--labels-border-top-style`]: tabStyles?.labelsBorder?.top?.style || null,
        [`--labels-border-top-width`]: tabStyles?.labelsBorder?.top?.width || null,
        [`--labels-border-right-color`]: tabStyles?.labelsBorder?.right?.color || null,
        [`--labels-border-right-style`]: tabStyles?.labelsBorder?.right?.style || null,
        [`--labels-border-right-width`]: tabStyles?.labelsBorder?.right?.width || null,
        [`--labels-border-bottom-color`]: tabStyles?.labelsBorder?.bottom?.color || null,
        [`--labels-border-bottom-style`]: tabStyles?.labelsBorder?.bottom?.style || null,
        [`--labels-border-bottom-width`]: tabStyles?.labelsBorder?.bottom?.width || null,
        [`--labels-border-left-color`]: tabStyles?.labelsBorder?.left?.color || null,
        [`--labels-border-left-style`]: tabStyles?.labelsBorder?.left?.style || null,
        [`--labels-border-left-width`]: tabStyles?.labelsBorder?.left?.width || null,
        [`--labels-border-active-top-color`]: tabStyles?.labelsBorderActive?.top?.color || null,
        [`--labels-border-active-top-style`]: tabStyles?.labelsBorderActive?.top?.style || null,
        [`--labels-border-active-top-width`]: tabStyles?.labelsBorderActive?.top?.width || null,
        [`--labels-border-active-right-color`]: tabStyles?.labelsBorderActive?.right?.color || null,
        [`--labels-border-active-right-style`]: tabStyles?.labelsBorderActive?.right?.style || null,
        [`--labels-border-active-right-width`]: tabStyles?.labelsBorderActive?.right?.width || null,
        [`--labels-border-active-bottom-color`]: tabStyles?.labelsBorderActive?.bottom?.color || null,
        [`--labels-border-active-bottom-style`]: tabStyles?.labelsBorderActive?.bottom?.style || null,
        [`--labels-border-active-bottom-width`]: tabStyles?.labelsBorderActive?.bottom?.width || null,
        [`--labels-border-active-left-color`]: tabStyles?.labelsBorderActive?.left?.color || null,
        [`--labels-border-active-left-style`]: tabStyles?.labelsBorderActive?.left?.style || null,
        [`--labels-border-active-left-width`]: tabStyles?.labelsBorderActive?.left?.width || null,
        [`--arrows-size`]: tabStyles?.arrowsSize || null,
        [`--arrows-padding`]: tabStyles?.arrowsPadding || null,
        [`--arrows-border-radius`]: tabStyles?.arrowsBorderRadius || null,
        [`--arrows-color`]: tabStyles?.arrowsColor || null,
        [`--arrows-bg-color`]: tabStyles?.arrowsBgColor || null,
        [`--arrows-hover-color`]: tabStyles?.arrowsHoverColor || null,
        [`--arrows-hover-bg-color`]: tabStyles?.arrowsHoverBgColor || null,
        [`--tabs-animation-duration`]: tabStyles?.tabsAnimationDuration || null,
        [`--tabs-animation-position-start`]: tabStyles?.tabsAnimationPositionStart || null,
        [`--tabs-animation-timing-function`]: tabStyles?.tabsAnimationTimingFunction || null,
        [`--scroller-width`]: tabStyles?.scrollerWidth || null,
        [`--scroller-items-number`]: tabStyles?.scrollerItemsNumber || null,
        [`--scroller-mobile-width`]: tabStyles?.scrollerMobileWidth || null,
        [`--scroller-mobile-items-number`]: tabStyles?.scrollerMobileItemsNumber || null,
    };
};
