<?php
// phpcs:ignoreFile
if ( function_exists( 'acf_add_local_field' ) ) :
	acf_add_local_field(
		array(
			'key'               => 'field_60256deb39103',
			'label'             => '',
			'name'              => 'cta_list',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => '',
			'min'               => 0,
			'max'               => 0,
			'layout'            => 'block',
			'button_label'      => 'Add link',
			'sub_fields'        => array(
				array(
					'key'               => 'field_60256e0339104',
					'label'             => 'Link',
					'name'              => 'link',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
				),
				array(
					'key'               => 'field_60256e0f39105',
					'label'             => 'Size',
					'name'              => 'size',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'-small'  => 'small',
						'-normal' => 'normal',
						'-large'  => 'large',
					),
					'allow_null'        => 0,
					'default_value'     => '-normal',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_60256e6fe7b8f',
					'label'             => 'Style',
					'name'              => 'style',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'-primary'   => 'primary',
//						'-inverted'  => 'inverted',
						'-secondary' => 'secondary',
						'-link'      => 'link',
						'-primary-inverted'   => 'primary-inverted',
						'-primary-inverted-light'   => 'primary-inverted-light',
						'-secondary-inverted' => 'secondary-inverted',
					),
					'allow_null'        => 0,
					'default_value'     => '',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_60256e6fe7b8fi',
					'label'             => 'Button Icon',
					'name'              => 'is_custom_icon',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'global' => 'Default',
						'yes'    => 'Custom',
						'no'     => 'No Icon',
					),
					'allow_null'        => 0,
					'default_value'     => '',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_605dcb99f55dec',
					'label'             => 'Icon',
					'name'              => 'icon',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60256e6fe7b8fi',
								'operator' => '==',
								'value'    => 'yes',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_605dcb87f55ddip',
					'label'             => 'Icon position',
					'name'              => 'icon_direction',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60256e6fe7b8fi',
								'operator' => '==',
								'value'    => 'yes',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'row-reverse' => 'left',
						'row'         => 'right',
					),
					'allow_null'        => 0,
					'default_value'     => 'row',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_605dcb87f55ddit',
					'label'             => 'Icon type',
					'name'              => 'icon_type',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60256e6fe7b8fi',
								'operator' => '==',
								'value'    => 'yes',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'custom' => 'custom',
					),
					'allow_null'        => 0,
					'default_value'     => 'custom',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_61a4f7777f34f',
					'label'             => 'Popup',
					'name'              => 'link_popup',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_61a4f7987f350',
							'label'             => 'Open Popup',
							'name'              => 'open_popup',
							'type'              => 'button_group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'disable' => 'disable',
								'content' => 'content',
								'video'   => 'video',
							),
							'allow_null'        => 0,
							'default_value'     => '',
							'layout'            => 'horizontal',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_61a4f7bf7f351',
							'label'             => 'Popup Content',
							'name'              => 'popup_content',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_61a4f7987f350',
										'operator' => '==',
										'value'    => 'content',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'full',
							'media_upload'      => 1,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_61a4f7e17f352',
							'label'             => 'Popup video type',
							'name'              => 'popup_video_type',
							'type'              => 'button_group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_61a4f7987f350',
										'operator' => '==',
										'value'    => 'video',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'choices'           => array(
								'url'  => 'url',
								'file' => 'file',
							),
							'allow_null'        => 0,
							'default_value'     => '',
							'layout'            => 'horizontal',
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_61a4f8077f353',
							'label'             => 'Video Link',
							'name'              => 'popup_video_url',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_61a4f7e17f352',
										'operator' => '==',
										'value'    => 'url',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_61a4f8207f354',
							'label'             => 'Video File',
							'name'              => 'popup_video_file',
							'type'              => 'file',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_61a4f7e17f352',
										'operator' => '==',
										'value'    => 'file',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'return_format'     => 'array',
							'library'           => 'all',
							'min_size'          => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
		)
	);
endif;
