<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_621509462f6c9',
			'title'                 => 'CPT: Testimonial',
			'fields'                => array(
				array(
					'key'               => 'field_62150952cb00e',
					'label'             => 'Company/Position',
					'name'              => 'company_position',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6215095dcb00f',
					'label'             => 'Quote',
					'name'              => 'quote',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6215096bcb010',
					'label'             => 'Full Story Type',
					'name'              => 'full_story_type',
					'type'              => 'button_group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'choices'           => array(
						'content' => 'content',
						'video'   => 'video',
					),
					'allow_null'        => 0,
					'default_value'     => 'text',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
				),
				array(
					'key'               => 'field_6215098fcb011',
					'label'             => 'Full Story CTA Label',
					'name'              => 'full_story_cta_label',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'default_value'     => 'View Full Testimonial',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6215099ecb012',
					'label'             => 'Full Story',
					'name'              => 'full_story',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_621509cacb013',
							'label'             => '',
							'name'              => 'content',
							'type'              => 'wysiwyg',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6215096bcb010',
										'operator' => '==',
										'value'    => 'content',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'default_value'     => '',
							'tabs'              => 'all',
							'toolbar'           => 'full',
							'media_upload'      => 1,
							'delay'             => 0,
						),
						array(
							'key'               => 'field_621509ebcb014',
							'label'             => 'Video',
							'name'              => 'video',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6215096bcb010',
										'operator' => '==',
										'value'    => 'video',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'ds_asset_type'     => '',
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_62150a10cb015',
									'label'             => 'Source',
									'name'              => 'popup_video_type',
									'type'              => 'button_group',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'ds_default_value'  => 0,
									'choices'           => array(
										'file' => 'internal',
										'url'  => 'external',
									),
									'allow_null'        => 0,
									'default_value'     => '',
									'layout'            => 'horizontal',
									'return_format'     => 'value',
								),
								array(
									'key'               => 'field_62150a5bcb016',
									'label'             => 'Video File',
									'name'              => 'popup_video_file',
									'type'              => 'file',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_62150a10cb015',
												'operator' => '==',
												'value'    => 'file',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'ds_default_value'  => 0,
									'return_format'     => 'array',
									'library'           => 'all',
									'min_size'          => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'field_62150a91cb017',
									'label'             => 'Video URL',
									'name'              => 'popup_video_url',
									'type'              => 'url',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_62150a10cb015',
												'operator' => '==',
												'value'    => 'url',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'ds_asset_type'     => '',
									'ds_default_value'  => 0,
									'default_value'     => '',
									'placeholder'       => '',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_62151d551852d',
					'label'             => 'Testimonial Main Image',
					'name'              => 'testimonial_main_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'ds_asset_type'     => '',
					'ds_default_value'  => 0,
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'testimonials',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);
endif;
